project_id = "vxflfyrwituvxhtjcwqg"

[functions.send-reminder-email]
verify_jwt = true

[functions.process-reminders]
verify_jwt = false

[functions.send-weekly-progress]
verify_jwt = false

[functions.send-partner-invite]
verify_jwt = true

[functions.send-household-invite]
verify_jwt = true

[functions.notify-task-assignment]
verify_jwt = true

[functions.lua-chat]
verify_jwt = true

[functions.sync-bird-contact]
verify_jwt = false

[functions.verify-household-invite]
verify_jwt = false

[functions.send-task-assignment-email]
verify_jwt = true

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false
