-- Add missing opstal field to profiles table
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS opstal_dak_type text;

-- Recreate admin_profiles_view with the new column
DROP VIEW IF EXISTS public.admin_profiles_view;

CREATE VIEW public.admin_profiles_view
WITH (security_invoker=off)
AS
SELECT
  p.id,
  p.user_id,
  p.phone,
  p.old_address,
  p.new_address,
  p.moving_date,
  p.key_handover_date,
  p.moving_type,
  p.renovation_type,
  p.needs_contractor_help,
  p.housing_property_type,
  p.has_garden,
  p.has_parking,
  p.is_vve,
  p.current_housing_situation,
  p.has_job,
  p.adults,
  p.children,
  p.pets,
  p.has_gas,
  p.has_smart_meter,
  p.glasvezel,
  p.works_from_home,
  p.building_access,
  p.insurance_value,
  p.building_year,
  p.garden_size,
  p.children_ages,
  p.energy_current_supplier,
  p.energy_connection_type,
  p.energy_estimated_gas,
  p.energy_estimated_electricity,
  p.has_fiber,
  p.internet_speed_preference,
  p.internet_bundle,
  p.floor_level,
  p.has_elevator,
  p.number_of_rooms,
  p.special_items,
  p.has_fragile_items,
  p.home_size_m2,
  p.forwarding_start_date,
  p.forwarding_duration,
  p.household_names,
  p.municipality,
  p.service_type,
  p.preferred_service_date,
  p.number_of_floors,
  p.number_of_bedrooms,
  p.garden_service_type,
  p.renovation_budget,
  p.moving_budget,
  p.renovation_start_date,
  -- Intake fields
  p.hypotheek_koopsom,
  p.hypotheek_werksituatie,
  p.hypotheek_heeft_partner,
  p.hypotheek_doel,
  p.notaris_dienst,
  p.taxatie_doel,
  p.taxatie_voorkeursdatum,
  p.slot_aantal_deuren,
  p.slot_veiligheidsniveau,
  p.slot_montage,
  p.verhuislift_locatie,
  p.bouwkundige_keuring_voorkeursdatum,
  p.opstal_dak_type,
  p.created_at,
  p.updated_at
FROM public.profiles p
WHERE public.is_admin_by_email();